### ISSUE TITLE
SeleniumTunnel not working for Firefox on OSX

### ISSUE THREAD

**Issue by rodneyrehm** [theintern/digdug#30]
Running tests locally (on OSX) in Chrome works fine

```js
config.tunnel = 'SeleniumTunnel';
config.tunnelOptions = {
  drivers: ['chrome'],
};
config.environments = [
  { browserName: 'chrome' },
];
```

But running tests locally (on OSX) in Firefox does not

```js
config.tunnel = 'SeleniumTunnel';
config.tunnelOptions = {
  drivers: ['firefox'],
};
config.environments = [
  { browserName: 'firefox' },
];
```

I see a few attempts at opening a Firefox browser window and the terminal shows the following output:

```
➜  ./node_modules/.bin/intern-runner config=test/firefox
Listening on 0.0.0.0:9000
Tunnel started
Suite firefox on any platform FAILED
UnknownError: [POST http://localhost:4444/wd/hub/session / {"desiredCapabilities":{"name":"test/firefox","idle-timeout":60,"browserName":"firefox"}}] Connection refused
  at Server.createSession  <node_modules/intern/node_modules/leadfoot/Server.js:324:15>
  at <node_modules/intern/lib/executors/Runner.js:200:23>
  at retry  <node_modules/intern/lib/util.js:804:13>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at process._tickCallback  <node.js:349:13>

TOTAL: tested 0 platforms, 0/0 tests failed; fatal error occurred
Error: Run failed due to one or more suite errors
  at emitLocalCoverage  <node_modules/intern/lib/executors/Executor.js:353:18>
  at finishSuite  <node_modules/intern/lib/executors/Executor.js:370:15>
  at <node_modules/intern/lib/executors/Executor.js:378:8>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at process._tickCallback  <node.js:349:13>
```

What am I missing here?

**Comment by jason0x43** [comment]
Yeah, that particular case needs more documentation. Three settings are required to use Firefox:

```js
{
    tunnelOptions: {
        // this tells SeleniumTunnel to download geckodriver
        drivers: [ 'firefox' ] 
    },

    environments: [
        // the `marionette: true` flag tells Selenium to use gecko driver
        // instead of Firefox driver, which it still defaults to
        { browserName: 'firefox', marionette: true }
    ],

    // geckodriver doesn't yet allow accessing global variables, so you can't use
    // code coverage instrumentation with it
    excludeInstrumenation: true
}
```

**Comment by rodneyrehm** [comment]
thx!
`excludeInstrumenation` -> `excludeInstrumentation` and it works for the most part. Except for scripts trying to access `document` et al, so basically not usable yet :(
