### ISSUE TITLE
Verbose flag does not work with Selenium 3.5.x+

### ISSUE THREAD

**Issue by shane-tomlinson** [theintern/digdug#50]
The fix for https://github.com/theintern/digdug/issues/43 in Selenium 3.4.0 no longer works in 3.5..

### 3.4.0 w/ `debug true`
> java -jar selenium-server-standalone-3.4.0.jar -debug true
13:12:22.755 INFO - Selenium build info: version: '3.4.0', revision: 'unknown'
13:12:22.756 INFO - Launching a standalone Selenium Server
2017-10-03 13:12:22.777:INFO::main: Logging initialized @238ms to org.seleniumhq.jetty9.util.log.StdErrLog
13:12:22.828 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
 registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform MAC
13:12:22.828 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
 registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform MAC
13:12:22.828 INFO - Driver class not found: com.opera.core.systems.OperaDriver
13:12:22.828 INFO - Driver provider com.opera.core.systems.OperaDriver registration is skipped:
Unable to create new instances on this machine.
13:12:22.828 INFO - Driver class not found: com.opera.core.systems.OperaDriver
13:12:22.828 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
2017-10-03 13:12:22.866:INFO:osjs.Server:main: jetty-9.4.3.v20170317
2017-10-03 13:12:22.902:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@14acaea5{/,null,AVAILABLE}
2017-10-03 13:12:22.933:INFO:osjs.AbstractConnector:main: Started ServerConnector@e25b2fe{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2017-10-03 13:12:22.933:INFO:osjs.Server:main: Started @395ms
13:12:22.933 INFO - Selenium Server is up and running

### 3.5.0  w/ `debug true`

> java -jar selenium-server-standalone-3.5.0.jar -debug true
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter 'true' but no main parameter was definedat com.beust.jcommander.JCommander.getMainParameter(JCommander.java:914)at com.beust.jcommander.JCommander.parseValues(JCommander.java:759)at com.beust.jcommander.JCommander.parse(JCommander.java:282)at com.beust.jcommander.JCommander.parse(JCommander.java:265)at com.beust.jcommander.JCommander.<init>(JCommander.java:210)at org.openqa.grid.selenium.GridLauncherV3$1.setConfiguration(GridLauncherV3.java:227)at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:155)at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:75)

### 3.5.0 w/ `debug`

> java -jar selenium-server-standalone-3.5.0.jar -debug
13:15:59.437 INFO - Selenium build info: version: '3.5.0', revision: '8def36e068'
13:15:59.438 INFO - Launching a standalone Selenium Server
2017-10-03 13:15:59.456:INFO::main: Logging initialized @223ms to org.seleniumhq.jetty9.util.log.StdErrLog
13:15:59.505 INFO - Driver class not found: com.opera.core.systems.OperaDriver
13:15:59.530 INFO - Driver provider class org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
 registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform MAC
13:15:59.530 INFO - Driver provider class org.openqa.selenium.edge.EdgeDriver registration is skipped:
 registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform MAC
13:15:59.558 INFO - Using the passthrough mode handler
2017-10-03 13:15:59.582:INFO:osjs.Server:main: jetty-9.4.5.v20170502
2017-10-03 13:15:59.601:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@3632be31{/,null,STARTING} has uncovered http methods for path: /
2017-10-03 13:15:59.606:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@3632be31{/,null,AVAILABLE}
2017-10-03 13:15:59.634:INFO:osjs.AbstractConnector:main: Started ServerConnector@32709393{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2017-10-03 13:15:59.634:INFO:osjs.Server:main: Started @402ms
13:15:59.634 INFO - Selenium Server is up and running

### 3.6.0 w/ `debug`
> java -jar selenium-server-standalone-3.6.0.jar -debug
13:16:03.228 INFO - Selenium build info: version: '3.6.0', revision: '6fbf3ec767'
13:16:03.229 INFO - Launching a standalone Selenium Server
2017-10-03 13:16:03.244:INFO::main: Logging initialized @222ms to org.seleniumhq.jetty9.util.log.StdErrLog
13:16:03.301 INFO - Driver class not found: com.opera.core.systems.OperaDriver
13:16:03.327 INFO - Driver provider class org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
 registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform MAC
13:16:03.327 INFO - Driver provider class org.openqa.selenium.edge.EdgeDriver registration is skipped:
 registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform MAC
13:16:03.357 INFO - Using the passthrough mode handler
2017-10-03 13:16:03.382:INFO:osjs.Server:main: jetty-9.4.5.v20170502
2017-10-03 13:16:03.407:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@57536d79{/,null,STARTING} has uncovered http methods for path: /
2017-10-03 13:16:03.411:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@57536d79{/,null,AVAILABLE}
2017-10-03 13:16:03.440:INFO:osjs.AbstractConnector:main: Started ServerConnector@5e853265{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2017-10-03 13:16:03.441:INFO:osjs.Server:main: Started @419ms
13:16:03.441 INFO - Selenium Server is up and running

**Comment by shane-tomlinson** [comment]
Closing, @jason0x43 opened #51.

**Comment by jason0x43** [comment]
Sorry, I didn't notice this one when I created #51.
